repos:
  - repo: local
    hooks:
      - id: jupytext
        name: jupytext
        entry: conda
        args: ["run", "-n", "dsp", "jupytext", "--sync", "**/*.ipynb"]
        always_run: true
        pass_filenames: false
        language: system